/**
 * Weekly summary from current DB state.
 */
import fs from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";
import {
  openDb,
  migrate,
  getMeta,
  getGaps,
  getEvents,
  getChineseModels,
} from "../packages/db/src/index.ts";

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const repoRoot = path.resolve(__dirname, "..");
const week = new Date().toISOString().slice(0, 10);
const outPath = path.join(repoRoot, "reports", `weekly-${week}.md`);

const { sqlite } = openDb();
migrate(sqlite);

const metaMap = getMeta(sqlite);
const highGaps = getGaps(sqlite).filter(
  (g) => g.priority === "high" && g.status !== "won",
);
const recentEvents = getEvents(sqlite, 15);
const cnModels = getChineseModels(sqlite);

const lines: string[] = [];
lines.push(`# Weekly CI Summary — ${week}`);
lines.push("");
lines.push(`As-of baseline: ${metaMap.as_of ?? "unknown"}`);
lines.push("");
lines.push("## Top actions for product / GTM / leadership");
lines.push("");
highGaps.slice(0, 5).forEach((g, i) => {
  lines.push(`${i + 1}. **[${g.priority.toUpperCase()}] ${g.title}** (${g.ownerTeam})`);
  lines.push(`   - ${g.recommendedAction.replace(/\s+/g, " ").trim()}`);
});
lines.push("");
lines.push("## High-priority open gaps");
lines.push("");
for (const g of highGaps) {
  lines.push(`- ${g.title} — score ${g.priorityScore} — ${g.grokStatus}`);
}
lines.push("");
lines.push("## Chinese velocity");
lines.push("");
for (const { model, companyName } of cnModels) {
  lines.push(
    `- ${model.name} (${companyName}) ${model.releaseDate ?? ""} ${model.openWeights ? "[open]" : "[closed]"}`,
  );
}
lines.push("");
lines.push("## Recent events");
lines.push("");
for (const { event: e } of recentEvents) {
  lines.push(`- ${e.occurredAt} [${e.severity}] ${e.title}`);
}
lines.push("");
lines.push("---");
lines.push("*Generated by `npm run report:weekly`.*");

fs.mkdirSync(path.dirname(outPath), { recursive: true });
fs.writeFileSync(outPath, lines.join("\n"));
sqlite.close();
console.log(`Wrote ${outPath}`);
